### ISSUE TITLE
Problema con plan contable por defecto.

### ISSUE THREAD

**Issue by Frodo17** [cuba-odoo/l10n-cuba#11]
Cuando instalas la LC, instala por defecto el Plan Contable Sector Privado y Cooperativo. Cuando escoges cambiarte al Plan Contable Empresas Publicas, muestra una alerta diciendo que:

¡El código de la cuenta tiene que ser único para cada empresa!

**Comment by hcalvofernandez** [comment]
solo sucede cuando cambias a plan contable empresarial . los demas hasta el gubernamental los cambia sin problemas
