### ISSUE TITLE
Calculo Base Impositiva para la Seguridad Social

### ISSUE THREAD

**Issue by hercab** [cuba-odoo/l10n-cuba#9]
Revisando la regla salarial con codigo BASE_IMPOSITIVA_SS, creo que debemos adoptar nombres mas especificos siempre que aplique segun Resolucion, por ejemplo en este caso se deberia diferenciar para el caso de los TCP en el nombre y tambien en el codigo.
 
En cuanto al calculo no me queda claro porque se deberia tomar el GROSS?

result = contract.regimen_contribution and int(contract.regimen_contribution) or GROSS

Entiendo que si es pluriempleo no hay necesidad de especificar un regimen de contribucion pero de no ser pluriempleo, el campo de regimen de contribucion deberia ser un campo obligatorio?

**Comment by asegurat15** [comment]
arreglado.
